[build]
jobs = 1
target = "x86_64-pc-windows-gnu"

[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc.exe"
rustflags = ["-C", "linker-flavor=gcc", "-C", "link-arg=-fuse-ld=lld", "-C", "debuginfo=0", "--cfg", "windows_slim_errors"]

[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "debuginfo=0"]

[env]
DATAIQ_LICENSE_SECRET = "dataiq-dev-secret-2026"
